config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :jobs, only: [:index, :show]
  resources :companies, only: [:index, :show]
  resources :applied_jobs

  namespace :company do 
    resources :jobs
    resources :applied_jobs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/applied_job.rb
class AppliedJob < ApplicationRecord
  JOINING_DURATION = ['Immediate', '1 Week', '15 Days', '1 Month', '2 Month']

  belongs_to :job
  belongs_to :user

  validates :cover_letter, :expected_ctc, :current_ctc, :contact_number, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs

  def self.ransackable_attributes(auth_object = nil)
    ["address", "contact", "created_at", "id", "name", "updated_at"]
  end
end

app/models/job.rb
class Job < ApplicationRecord

  JOB_TYPE = ['Contract', 'Fulltime', 'Part time', 'Internship'].freeze
  JOB_LOCATION = ['Remote', 'Onsite']
  APPLICABLE_FOR = ['Freshers', 'Intermediate', 'Experienced', 'Expert', 'Open for all']
  SALARY_RANGE = ['$1000-$2500', '$2500-$5000', '$5000-$10000', '> $10000', 'Hourly']

  has_many :applied_jobs
  belongs_to :company
  
  validates :title, presence: true, uniqueness: true
  validates :description, :job_location, :job_type, 
            :applicable_for, :salary_range, :total_positions, presence: true

  scope :remote_jobs, -> { where(job_location: 'Remote') }
  scope :onsight_jobs, -> { where(job_location: 'Onsight') }

  def posted_by
    User.where(role: 'employeer').find(posted_by_id)
  end

  before_create :generate_uuid

  def generate_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
  
  belongs_to :company, optional: true

  validate :company_required_if_employeer

  def employeer?
    role == 'employeer'
  end

  def job_seeker?
    role == 'job_seeker'
  end

  def name
    "#{first_name} #{last_name}".strip
  end

  private

  def company_required_if_employeer
    if employeer? && company.nil?
      errors.add(:company, "must exist if user is an employer")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  private

  def current_company
    if user_signed_in? && current_user.employeer?
      current_user.company
    end
  end

  def current_employeer
    if user_signed_in? && current_user.employeer?
      current_user
    end
  end
end

app/controllers/applied_jobs_controller.rb
class AppliedJobsController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find_by(uuid: params[:job_id])
    @job_application = AppliedJob.new
  end

  def create
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @q = Company.includes(:jobs).ransack(params[:q])
    @companies = @q.result
  end

  def show
    @company = Company.find(params[:id])
    @jobs = @company.jobs
  end
end

app/controllers/company/jobs_controller.rb
class Company::JobsController < ApplicationController
  before_action :authenticate_user!

  def index
    @jobs = current_company.jobs
  end

  def new
    @job = current_company.jobs.new
  end

  def create
    @job = current_company.jobs.new(job_params)
  end

  def show
    @job = current_company.jobs.find(params[:id])
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :posted_by_id, :applicable_for, :job_type, :job_location, :salary_range, :total_positions)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    if params[:type].present?
      @jobs = Job.includes(:company).send("#{params[:type]}_jobs")
    else
      @jobs = Job.includes(:company).find_each
    end
  end

  def show
    @job = Job.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/applied_jobs/_form.html.erb
<div class="card shadow">
  <div class="card-body">
    <h3 class="text-primary mb-2">Apply for <%= @job.title %></h3>
    <%= form_with(model: job_application) do |form| %>
      <%= form.hidden_field :job_id, value: @job.id %>
      <div class="form-group">
        <%= form.label :cover_letter, class: 'mb-2 mt-3 fw-bold' %>
        <%= form.text_area :cover_letter, class: 'form-control', rows: 10 %>
      </div>
      <div class="form-group">
        <%= form.label 'Current CTC', class: 'mb-2 mt-3 fw-bold' %>
        <%= form.text_field :current_ctc, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label 'Expected CTC', class: 'mb-2 mt-3 fw-bold' %>
        <%= form.text_field :expected_ctc, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label 'Contact Number', class: 'mb-2 mt-3 fw-bold' %>
        <%= form.text_field :contact_number, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label 'When you will be able to join?', class: 'mb-2 mt-3 fw-bold' %>
        <%= form.select :estimated_joining_within, options_for_select(AppliedJob::JOINING_DURATION, selected: job_application.estimated_joining_within), {}, { class: 'form-select' } %>
      </div>
      <div class="form-group">
        <%= form.label 'Serving Notice Period?', class: 'mb-2 mt-3 fw-bold' %>
        <%= form.check_box :serving_notice_period %>
      </div>
      <div class="form-group mt-4 mb-5">
        <%= form.submit 'Apply To Job', class: 'btn btn-primary btn-lg' %>
        <%= link_to 'Not Now', request.referrer, class: 'btn btn-outline-primary btn-lg'  %>
      </div>
    <% end %>
  </div>
</div>

app/views/applied_jobs/new.html.erb
<div class="row">
  <div class="col-lg-8 mt-5">
    <%= render 'form', job_application: @job_application %>
  </div>
  <div class="col-lg-4 mt-5">
    <div class="card shadow">
      <div class="card-body">
        <h4 class="text-primary card-title">Company Details</h4>
        <p class="lead fw-bold"><span class="text-secondary">Name: </span><%= @job.company.name %></p>
        <p class="lead fw-bold"><span class="text-secondary"> Posted By: </span><%= @job.posted_by.name %></p>
        <p class="lead fw-bold"><span class="text-secondary"> Company Address: </span><%= @job.company.address %></p>
        <p class="lead fw-bold"><span class="text-secondary"> Contacts: </span><%= "#{@job.company.contact}, #{@job.posted_by.contact_number}" %></p>
      </div>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="mt-5 mb-5">
  <div class="card shadow">
    <h1 class="text-center mb-4 mt-4">Search Companies</h1>
    <div class="card-body">
      <%= search_form_for @q, url: companies_path do |form| %>
        <div class="input-group mb-5">
          <%= form.text_field :name_cont, class: 'form-control form-control-lg', "aria-describedby" =>"button-addon2" %>
          <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
            <i class="bi-search"></i> Search
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <% @companies.each do |company| %>
    <div class="col-lg-4">
      <div class="card shadow mb-5">
        <div class="card-body text-center">
          <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrq8mdQOGc0FwzK4t6d7dn6SdSaCJXbyGb0g&s" %>
          <p class="lead fw-bold text-primary"><%= company.name %></p>
          <p class="lead"><i class="bi-phone"></i> <%= company.contact %></p>
          <%= link_to 'View Company', company, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/companies/show.html.erb
<div class="mt-5">
  <h1 class="text-primary"><%= @company.name %></h1>
  <p class="lead fw-bold text-secondary"><i class="bi-pin-map-fill"></i> <%= @company.address %></p>
  <p class="lead fw-bold text-secondary"><i class="bi-phone"></i> <%= @company.contact %></p>
  <hr>
  <% if @jobs.present? %>
    <h4 class="text-secondary mt-4 mb-4">Open jobs at <%= @company.name %></h4>
    <% @jobs.each do |job| %>
      <div class="card shadow mb-3">
        <div class="card-body">
          <p class="lead fw-bold text-primary"><%= job.title %></p>
          <div class="row">
            <div class="col-lg-3">
              <p class="fw-bold text-secondary my-1">Applicable for</p>
              <small class=""><%= job.applicable_for %></small>
            </div>
            <div class="col-lg-3">
              <p class="fw-bold text-secondary my-1">Salary Range</p>
              <small class=""><%= job.salary_range %></small>
            </div>
            <div class="col-lg-3">
              <p class="fw-bold text-secondary my-1">Total Positions</p>
              <small class=""><%= job.total_positions %></small>
            </div>
            <div class="col-lg-6 mt-3 mb-2">
              <%= link_to 'Apply to this job', new_applied_job_path(job_id: job.uuid), class: 'btn btn-primary' %>
              <%= link_to 'View job', job, class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/company/jobs/_form.html.erb
<div class="card shadow">
  <div class="card-body">
    <%= form_with(model: [:company, job]) do |form| %>
      <%= form.hidden_field :posted_by_id, value: current_user.id %>
      <div class="form-group">
        <%= form.label :title, class: 'mb-2 mt-3 fw-bold' %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :description, class: 'mb-2 mt-3 fw-bold' %>
        <%= form.text_area :description, class: 'form-control', rows: 10 %>
      </div>
      <div class="form-group row">
        <div class="col-lg-6">
          <%= form.label :job_type, class: 'mb-2 mt-3 fw-bold' %>
          <%= form.select :job_type, options_for_select(Job::JOB_TYPE, selected: job.job_type), {}, { class: 'form-select' } %>
        </div>
        <div class="col-lg-6">
          <%= form.label :job_location, class: 'mb-2 mt-3 fw-bold' %>
          <%= form.select :job_location, options_for_select(Job::JOB_LOCATION, selected: job.job_location), {}, { class: 'form-select' } %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-lg-6">
          <%= form.label :applicable_for, class: 'mb-2 mt-3 fw-bold' %>
          <%= form.select :applicable_for, options_for_select(Job::APPLICABLE_FOR, selected: job.applicable_for), {}, { class: 'form-select' } %>
        </div>
        <div class="col-lg-6">
          <%= form.label :salary_range, class: 'mb-2 mt-3 fw-bold' %>
          <%= form.select :salary_range, options_for_select(Job::SALARY_RANGE, selected: job.salary_range), {}, { class: 'form-select' } %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :total_positions, class: 'mb-2 mt-3 fw-bold' %>
        <%= form.number_field :total_positions, min: 1, class: 'form-control' %>
      </div>
      <div class="form-group mt-4 mb-5">
        <%= form.submit 'Post Job', class: 'btn btn-primary btn-lg' %>
        <%= link_to 'Back to List', company_jobs_path, class: 'btn btn-outline-primary btn-lg'  %>
      </div>
    <% end %>
  </div>
</div>

app/views/company/jobs/index.html.erb
<div class="row mt-5">
  <div class="col-lg-8 mx-auto">

    <%= link_to "Post New Job", new_company_job_path, class: "btn btn-primary btn-lg mb-4 shadow" %>

    <% @jobs.each do |job| %>
      <div class="card shadow mb-3">
        <div class="card-body">
          <p class="lead fw-bold text-primary"><%= job.title %></p>
          <div class="row">
            <div class="col-lg-3">
              <p class="fw-bold text-secondary my-1">Applicable for</p>
              <small class=""><%= job.applicable_for %></small>
            </div>
            <div class="col-lg-3">
              <p class="fw-bold text-secondary my-1">Salary Range</p>
              <small class=""><%= job.salary_range %></small>
            </div>
            <div class="col-lg-3">
              <p class="fw-bold text-secondary my-1">Total Positions</p>
              <small class=""><%= job.total_positions %></small>
            </div>
            <div class="col-lg-3">
              <p class="fw-bold text-secondary my-1">Posted On</p>
              <small class=""><%= job.created_at.strftime("%d %b, %Y") %></small>
            </div>
            <div class="col-lg-6">
              <%= link_to 'View job', job, class: 'btn btn-primary mt-3' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/company/jobs/new.html.erb
<div class="row">
  <div class="card mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-secondary">Create a new job</h2>
      <p class="fw-bold lead">Fields marked as <span class="text-danger">*</span> are the required fields.</p>
    </div>
  </div>
  <%= render 'form', job: @job %>
</div>

app/views/home/index.html.erb
<h1 class="text-center">Find Your Dream Jobs Here</h1>

<div class="row mt-5">
  <div class="col-lg-10 mx-auto">
    <div class="row">
      <div class="col-lg-4">
        <%= link_to companies_path do %>
          <div class="card rounded-0 shadow">
            <div class="card-body text-center">
              <h3 class="text-primary">Total Companies</h3>
              <p class="lead"><%= Company.count %></p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-lg-4">
        <%= link_to jobs_path(type: 'remote') do %>
          <div class="card rounded-0 shadow">
            <div class="card-body text-center">
              <h3 class="text-primary">Remote Jobs</h3>
              <p class="lead"><%= pluralize(Job.remote_jobs.count, 'Job') %></p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-lg-4">
        <%= link_to jobs_path(type: 'onsight') do %>
          <div class="card rounded-0 shadow">
            <div class="card-body text-center">
              <h3 class="text-primary">Onsight Jobs</h3>
              <p class="lead"><%= pluralize(Job.onsight_jobs.count, 'Job') %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<% if @jobs.present? %>
  <h1 class="text-center">Hey! We got total <%= pluralize(@jobs.count, "#{(params[:type] || '').titleize} Job") %> For You</h1>
  <div class="row mt-5">
    <div class="col-lg-8 mx-auto">
      <% @jobs.each do |job| %>
        <div class="card shadow mb-3">
          <div class="card-body">
            <p class="lead fw-bold text-primary"><%= job.title %></p>
            <div class="row">
              <div class="col-lg-3">
                <p class="fw-bold text-secondary my-1">Applicable for</p>
                <small class=""><%= job.applicable_for %></small>
              </div>
              <div class="col-lg-3">
                <p class="fw-bold text-secondary my-1">Salary Range</p>
                <small class=""><%= job.salary_range %></small>
              </div>
              <div class="col-lg-3">
                <p class="fw-bold text-secondary my-1">Total Positions</p>
                <small class=""><%= job.total_positions %></small>
              </div>
              <div class="col-lg-3">
                <p class="fw-bold text-secondary my-1">Company</p>
                <small class=""><%= link_to job.company.name, job.company %></small>
              </div>
              <div class="col-lg-6">
                <%= link_to 'Apply to this job', new_applied_job_path(job_id: job.uuid), class: 'btn btn-primary' %>
                <%= link_to 'View job', job, class: 'btn btn-primary' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <h1 class="text-center">Sorry! No <%= "#{(params[:type] || '').titleize} Jobs" %> at the moment</h1>
<% end %>

app/views/jobs/show.html.erb
<div class="row">
  <div class="col-lg-9">
    <h2 class="text-primary mt-4 mb-5"><%= @job.title %></h2>
    <p class="lead text-secondary"><%= @job.description %></p>
    <p class="lead text-secondary fw-bold">Total Positions: <%= @job.total_positions %></p>
    <p class="lead text-secondary fw-bold">Who can Apply: <%= @job.applicable_for %></p>
    <p class="lead text-secondary fw-bold">Salary Range: <%= @job.salary_range %></p>
    <p class="lead text-secondary fw-bold">Job Type: <%= @job.job_type %></p>
    <p class="lead text-secondary fw-bold">Location: <%= @job.job_location %></p>
  </div>
  <div class="col-lg-3">
  </div>
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobPosting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">JobListing</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/companies">Companies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/jobs?type=remote">Remote Jobs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/jobs?type=onsight">Onsite Jobs</a>
        </li>
      </ul>
    </div>
  </div>
</nav>